services:
  bot:
    build: .
    container_name: rowelltz_tg_bot
    restart: unless-stopped
    env_file:
      - ./.env
    # бот должен стартовать ПОСЛЕ того,
    # как запустится сервис 'redis'.
    depends_on:
      - redis
    ports:
      # Внешний порт 3000 на localhost хоста ведёт к порту 3000 контейнера
      - "127.0.0.1:3000:3000"

  # сервис для Redis
  redis:
    image: redis:7-alpine
    container_name: rw_tg_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "127.0.0.1:6379:6379"
    # Эта секция "пробрасывает" данные Redis,
    # чтобы при перезапуске контейнера данные не терялись.
    volumes:
      - redis_data:/data


# именованный том для хранения данных Redis
volumes:
  redis_data: